---
abstract: 'Load a McBain API as a RESTful PSGI web service'
author:
  - 'Ido Perlmuter <ido@ido50.net>'
build_requires:
  HTTP::Request: 0
  McBain: 0
  Plack::Test: 0
  Test::More: 0
  lib: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: McBain-WithPSGI
requires:
  Carp: 0
  JSON: 0
  Plack::Component: 0
  Plack::Request: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  homepage: https://github.com/ido50/McBain-WithPSGI
  repository: https://github.com/ido50/McBain-WithPSGI.git
version: 1.000000
